# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525ad05ce20c0783aa0c1a92e7bb468d407e3a11c02084e201af6a996302af3d13ffa399b25d6dcd79d46393352e34cb73f2f35d8fd6bdd0963de51d468ca72e

test:
  secret_key_base: 563bf60467a853214e16350014785bc36d103f1c2f84a95b251e261e903846c71a45baefb787753354ab9465f007fb393d3cd0661dfa25d13818674f7339d930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
